resources:
- new-deployment.yaml

configMapGenerator:
- name: new-config
  literals:
  - welcomeMessage=Welcome to pod 6

secretGenerator:
- name: new-secret
  literals:
  - username=admin
  - password=password@121

generatorOptions:
  disableNameSuffixHash: false
