apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-app-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new-app
  template:
    metadata:
      labels:
        app: new-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: WELCOME_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: new-config
              key: welcomeMessage
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: new-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: new-secret
              key: password
